/*
 * DO NOT EDIT THIS FILE - Generated by @gcoredev/FastEdge-sdk-js
 *
 * It will be overwritten on the next build.
 */

const staticAssetManifest = {
  '/fastedge-init-http.png': { assetKey: '/fastedge-init-http.png', contentType: 'image/png', fileInfo: { size: 10463, hash: 'f65c5f7064654ae2c7e59fa38202ee3eb97a926118621a90f77a18b33f01fb25', lastModifiedTime: 1758124611, assetPath: './test-public/fastedge-init-http.png' }, lastModifiedTime: 1758124611, type: 'wasm-inline' },
  '/fastedge-init-static.png': { assetKey: '/fastedge-init-static.png', contentType: 'image/png', fileInfo: { size: 30966, hash: '88a24fdbb8a4e865f87498db130975053edb44938eb3cca63a1223beb5b4fa6c', lastModifiedTime: 1758124611, assetPath: './test-public/fastedge-init-static.png' }, lastModifiedTime: 1758124611, type: 'wasm-inline' },
  '/favicon.svg': { assetKey: '/favicon.svg', contentType: 'image/svg+xml', fileInfo: { size: 1467, hash: 'fe1929c8ac79ce6d8def7021fc4bf8047dae4b6d1a27cf1df9ccfdb687f28a2d', lastModifiedTime: 1758124611, assetPath: './test-public/favicon.svg' }, lastModifiedTime: 1758124611, type: 'wasm-inline' },
  '/robots.txt': { assetKey: '/robots.txt', contentType: 'text/plain', fileInfo: { size: 0, hash: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855', lastModifiedTime: 1758124661, assetPath: './test-public/robots.txt' }, lastModifiedTime: 1758124661, type: 'wasm-inline' },
};

export { staticAssetManifest };
