// Generated by `wit-bindgen` 0.16.0. DO NOT EDIT!
#ifndef __BINDINGS_HTTP_REACTOR_H
#define __BINDINGS_HTTP_REACTOR_H
#ifdef __cplusplus
extern "C" {
#endif

#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <stdbool.h>

typedef struct {
  uint8_t*ptr;
  size_t len;
} http_reactor_string_t;

typedef struct {
  bool is_some;
  http_reactor_string_t val;
} local_bindings_dictionary_option_string_t;

// Imported Functions from `local:bindings/dictionary`
// Get the value associated with the specified `key`
// 
// Returns `ok(none)` if the key does not exist.
extern bool local_bindings_dictionary_get(http_reactor_string_t *name, http_reactor_string_t *ret);

// Helper Functions

void local_bindings_dictionary_option_string_free(local_bindings_dictionary_option_string_t *ptr);

// Transfers ownership of `s` into the string `ret`
void http_reactor_string_set(http_reactor_string_t *ret, char*s);

// Creates a copy of the input nul-terminate string `s` and
// stores it into the component model string `ret`.
void http_reactor_string_dup(http_reactor_string_t *ret, const char*s);

// Deallocates the string pointed to by `ret`, deallocating
// the memory behind the string.
void http_reactor_string_free(http_reactor_string_t *ret);

#ifdef __cplusplus
}
#endif
#endif
