// Generated by `wit-bindgen` 0.16.0. DO NOT EDIT!
#include "http_reactor.h"


__attribute__((__import_module__("local:bindings/dictionary"), __import_name__("get")))
extern void __wasm_import_local_bindings_dictionary_get(int32_t, int32_t, int32_t);

__attribute__((__weak__, __export_name__("cabi_realloc")))
void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size) {
  (void) old_size;
  if (new_size == 0) return (void*) align;
  void *ret = realloc(ptr, new_size);
  if (!ret) abort();
  return ret;
}

// Helper Functions

void local_bindings_dictionary_option_string_free(local_bindings_dictionary_option_string_t *ptr) {
  if (ptr->is_some) {
    http_reactor_string_free(&ptr->val);
  }
}

void http_reactor_string_set(http_reactor_string_t *ret, char*s) {
  ret->ptr = (uint8_t*) s;
  ret->len = strlen(s);
}

void http_reactor_string_dup(http_reactor_string_t *ret, const char*s) {
  ret->len = strlen(s);
  ret->ptr = cabi_realloc(NULL, 0, 1, ret->len * 1);
  memcpy(ret->ptr, s, ret->len * 1);
}

void http_reactor_string_free(http_reactor_string_t *ret) {
  if (ret->len > 0) {
    free(ret->ptr);
  }
  ret->ptr = NULL;
  ret->len = 0;
}

// Component Adapters

bool local_bindings_dictionary_get(http_reactor_string_t *name, http_reactor_string_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[12];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_local_bindings_dictionary_get((int32_t) (*name).ptr, (int32_t) (*name).len, ptr);
  local_bindings_dictionary_option_string_t option;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      option.is_some = false;
      break;
    }
    case 1: {
      option.is_some = true;
      option.val = (http_reactor_string_t) { (uint8_t*)(*((int32_t*) (ptr + 4))), (size_t)(*((int32_t*) (ptr + 8))) };
      break;
    }
  }
  *ret = option.val;
  return option.is_some;
}

extern void __component_type_object_force_link_http_reactor(void);
void __component_type_object_force_link_http_reactor_public_use_in_this_compilation_unit(void) {
  __component_type_object_force_link_http_reactor();
}
